print ("Content-type:text/html\r\n\r\n")
print ('<html>')
print ('<head>')
print ('<title>Hello Word!!!</title>')
print ('</head>')
print ('<body>')
print ('<h2>Hello dear evaluator from Python CGI</h2>')
print ('</body>')
print ('</html>')
